{
 "title": "aoss dashobard ec2 instance Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Instance Health(up/down)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"ec2-node\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"ec2-node\", device!=\"lo\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"ec2-node\", device!=\"lo\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_load1{job=\"ec2-node\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO Pressure (Read + Write)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "(\r\n  1 - (\r\n    node_filesystem_avail_bytes{job=\"ec2-node\", mountpoint=\"/\"}\r\n    /\r\n    node_filesystem_size_bytes{job=\"ec2-node\", mountpoint=\"/\"}\r\n  )\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "(\r\n  1 - (\r\n    node_memory_MemAvailable_bytes{job=\"ec2-node\"}\r\n    /\r\n    node_memory_MemTotal_bytes{job=\"ec2-node\"}\r\n  )\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "100 - (\r\n  avg by (instance)(\r\n    rate(node_cpu_seconds_total{job=\"ec2-node\", mode=\"idle\"}[5m])\r\n  ) * 100\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}